language: node_js
node_js:
  - "12"
  - "node"
before_install:
  - npm i mocha
  - npm i
  - npm install -g codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
script:
  - npm run test
  - npm run coverage
  - bash <(curl -s https://codecov.io/bash) -cF javascript